/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Live */
    get: operations["live_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations["ready_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_v1_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Events */
    get: operations["events_v1_events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/incidents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Incidents */
    get: operations["incidents_v1_incidents_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/incidents/{incident_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detail */
    get: operations["detail_v1_incidents__incident_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Incident */
    patch: operations["update_incident_v1_incidents__incident_id__patch"];
    trace?: never;
  };
  "/v1/incidents/{incident_id}/decisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Decision */
    post: operations["decision_v1_incidents__incident_id__decisions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/incidents/{incident_id}/notes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Note */
    post: operations["add_note_v1_incidents__incident_id__notes_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Jobs */
    get: operations["jobs_v1_jobs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/jobs/{job_id}/retry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Retry Job */
    post: operations["retry_job_v1_jobs__job_id__retry_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_v1_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Overview */
    get: operations["overview_v1_overview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/services": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Services */
    get: operations["services_v1_services_get"];
    put?: never;
    /** Create Service */
    post: operations["create_service_v1_services_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/signals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Signals */
    post: operations["signals_v1_signals_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/stream": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Stream */
    get: operations["stream_v1_stream_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ActionRead */
    ActionRead: {
      /** Id */
      id: string;
      /** Risk */
      risk: string;
      /** Steps */
      steps: string[];
      /** Title */
      title: string;
    };
    /** AnalysisRead */
    AnalysisRead: {
      /** Actions */
      actions: components["schemas"]["ActionRead"][];
      /** Burn Rates */
      burn_rates: {
        [key: string]: number;
      };
      /** Engine */
      engine: string;
      /** Evidence */
      evidence: string[];
      /** Model Status */
      model_status: string;
      /** Model Summary */
      model_summary: string | null;
      /** Severity */
      severity: string;
      /** Summary */
      summary: string;
    };
    /** Decision */
    Decision: {
      /**
       * Action Id
       * @enum {string}
       */
      action_id: "inspect-deployment" | "inspect-dependencies" | "review-capacity";
      /**
       * Outcome
       * @enum {string}
       */
      outcome: "approved" | "rejected";
      /** Reason */
      reason: string;
      /** Version */
      version: number;
    };
    /** EventRead */
    EventRead: {
      /** Actor */
      actor: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Details */
      details: {
        [key: string]: unknown;
      };
      /** Id */
      id: number;
      /** Incident Id */
      incident_id: string | null;
      /** Kind */
      kind: string;
      /** Message */
      message: string;
      /** Tenant Id */
      tenant_id: string;
    };
    /** Evidence */
    Evidence: {
      /** Deployment */
      deployment?: string | null;
      /** Error Rate 1H */
      error_rate_1h: number;
      /**
       * Error Rate 5M
       * @description Percentage, e.g. 2.5 = 2.5%
       */
      error_rate_5m: number;
      /** Error Rate 6H */
      error_rate_6h: number;
      /** Latency P95 Ms */
      latency_p95_ms: number;
      /** Observed At */
      observed_at?: string | null;
      /** Requests Per Minute */
      requests_per_minute: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HistoryDay */
    HistoryDay: {
      /** Date */
      date: string;
      /** Opened */
      opened: number;
      /** Resolved */
      resolved: number;
    };
    /** IncidentDetailRead */
    IncidentDetailRead: {
      /** Acknowledged At */
      acknowledged_at: string | null;
      analysis: components["schemas"]["AnalysisRead"] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Events */
      events: components["schemas"]["EventRead"][];
      evidence: components["schemas"]["Evidence"];
      /** Fingerprint */
      fingerprint: string;
      /** Id */
      id: string;
      /** Owner */
      owner: string | null;
      /** Resolved At */
      resolved_at: string | null;
      /** Service Id */
      service_id: string;
      /**
       * Severity
       * @enum {string}
       */
      severity: "SEV1" | "SEV2" | "SEV3";
      /** Signal Count */
      signal_count: number;
      /**
       * Status
       * @enum {string}
       */
      status: "open" | "acknowledged" | "mitigating" | "resolved";
      /** Tenant Id */
      tenant_id: string;
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Version */
      version: number;
    };
    /** IncidentPage */
    IncidentPage: {
      /** Items */
      items: components["schemas"]["IncidentRead"][];
      /** Next Cursor */
      next_cursor: string | null;
    };
    /** IncidentRead */
    IncidentRead: {
      /** Acknowledged At */
      acknowledged_at: string | null;
      analysis: components["schemas"]["AnalysisRead"] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      evidence: components["schemas"]["Evidence"];
      /** Fingerprint */
      fingerprint: string;
      /** Id */
      id: string;
      /** Owner */
      owner: string | null;
      /** Resolved At */
      resolved_at: string | null;
      /** Service Id */
      service_id: string;
      /**
       * Severity
       * @enum {string}
       */
      severity: "SEV1" | "SEV2" | "SEV3";
      /** Signal Count */
      signal_count: number;
      /**
       * Status
       * @enum {string}
       */
      status: "open" | "acknowledged" | "mitigating" | "resolved";
      /** Tenant Id */
      tenant_id: string;
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Version */
      version: number;
    };
    /** JobRead */
    JobRead: {
      /** Attempts */
      attempts: number;
      /**
       * Available At
       * Format: date-time
       */
      available_at: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Error */
      error: string | null;
      /** Id */
      id: string;
      /** Incident Id */
      incident_id: string;
      /** Lease Until */
      lease_until: string | null;
      /** Status */
      status: string;
      /** Tenant Id */
      tenant_id: string;
    };
    /** Login */
    Login: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** Note */
    Note: {
      /** Message */
      message: string;
    };
    /** OverviewRead */
    OverviewRead: {
      /** Active Incidents */
      active_incidents: number;
      /**
       * As Of
       * Format: date-time
       */
      as_of: string;
      /** Critical Incidents */
      critical_incidents: number;
      /** History */
      history: components["schemas"]["HistoryDay"][];
      /** Jobs */
      jobs: {
        [key: string]: number;
      };
      /** Mttr Minutes */
      mttr_minutes: number | null;
      /** Resolved 30D */
      resolved_30d: number;
      /** Service Count */
      service_count: number;
      /** Services */
      services: components["schemas"]["ServiceRisk"][];
      /** Unaffected Services */
      unaffected_services: number;
    };
    /** ServiceCreate */
    ServiceCreate: {
      /** Dependencies */
      dependencies?: string[];
      /**
       * Description
       * @default
       */
      description: string;
      /** Name */
      name: string;
      /**
       * Slo
       * @default 99.9
       */
      slo: number;
      /** Slug */
      slug: string;
      /** Team */
      team: string;
      /**
       * Tier
       * @default 1
       */
      tier: number;
    };
    /** ServiceRead */
    ServiceRead: {
      /** Dependencies */
      dependencies: string[];
      /** Description */
      description: string;
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Slo */
      slo: number;
      /** Slug */
      slug: string;
      /** Team */
      team: string;
      /** Tenant Id */
      tenant_id: string;
      /** Tier */
      tier: number;
    };
    /** ServiceRisk */
    ServiceRisk: {
      /** Active */
      active: number;
      /** Burn Rate */
      burn_rate: number;
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Slo */
      slo: number;
      /** Team */
      team: string;
    };
    /** ServiceView */
    ServiceView: {
      /** Active Incidents */
      active_incidents: number;
      /** Dependencies */
      dependencies: string[];
      /** Description */
      description: string;
      /** Id */
      id: string;
      latest_evidence: components["schemas"]["Evidence"] | null;
      /** Name */
      name: string;
      /** Slo */
      slo: number;
      /** Slug */
      slug: string;
      /** Team */
      team: string;
      /** Tenant Id */
      tenant_id: string;
      /** Tier */
      tier: number;
    };
    /** Signal */
    Signal: {
      evidence: components["schemas"]["Evidence"];
      /** Fingerprint */
      fingerprint: string;
      /** Service Id */
      service_id: string;
      /** Title */
      title: string;
    };
    /** SignalReceipt */
    SignalReceipt: {
      /** Correlated */
      correlated: boolean;
      /** Incident Id */
      incident_id: string;
      /** Job Id */
      job_id: string;
      /** Replayed */
      replayed: boolean;
    };
    /** Transition */
    Transition: {
      /**
       * Note
       * @default
       */
      note: string;
      /**
       * Status
       * @enum {string}
       */
      status: "acknowledged" | "mitigating" | "resolved";
      /** Version */
      version: number;
    };
    /** UserRead */
    UserRead: {
      /** Email */
      email: string;
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Role */
      role: string;
      /** Tenant Id */
      tenant_id: string;
      /** Workspace */
      workspace: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  live_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  ready_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  login_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Login"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  events_v1_events_get: {
    parameters: {
      query?: {
        after?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  incidents_v1_incidents_get: {
    parameters: {
      query?: {
        status?: string | null;
        before?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IncidentPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  detail_v1_incidents__incident_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        incident_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IncidentDetailRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_incident_v1_incidents__incident_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        incident_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Transition"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IncidentRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  decision_v1_incidents__incident_id__decisions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        incident_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Decision"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_note_v1_incidents__incident_id__notes_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        incident_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Note"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  jobs_v1_jobs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobRead"][];
        };
      };
    };
  };
  retry_job_v1_jobs__job_id__retry_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  me_v1_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
    };
  };
  overview_v1_overview_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OverviewRead"];
        };
      };
    };
  };
  services_v1_services_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceView"][];
        };
      };
    };
  };
  create_service_v1_services_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ServiceCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  signals_v1_signals_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Signal"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SignalReceipt"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  stream_v1_stream_get: {
    parameters: {
      query?: {
        after?: number;
      };
      header?: {
        "last-event-id"?: number | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
